# Generated by Django 4.2.4 on 2023-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boo_name', models.CharField(max_length=255)),
                ('boo_author', models.CharField(max_length=255)),
                ('boo_type', models.CharField(max_length=255)),
                ('boo_year', models.CharField(max_length=255)),
                ('boo_image', models.ImageField(upload_to='books')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
